apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "application-gateway-kubernetes-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.armAuth }}
    {{- if eq .Values.armAuth.type "aadPodIdentity" }}
    {{- if .Values.armAuth.workloadIdentityEnabled }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ required "armAuth.identityClientID is required if using AAD-Pod-Identity" .Values.armAuth.identityClientID }}
    {{- end }}
    {{- end }}
    {{- end }}
  name: {{ template "application-gateway-kubernetes-ingress.serviceaccountname" . }}