apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition 
metadata: 
  name: azureapplicationgatewayinstanceupdatestatuses.appgw.ingress.azure.io 
spec: 
  group: appgw.ingress.azure.io 
  version: v1beta1
  scope: Cluster 
  names: 
    plural: azureapplicationgatewayinstanceupdatestatuses
    singular: azureapplicationgatewayinstanceupdatestatus
    kind: AzureApplicationGatewayInstanceUpdateStatus
    shortNames: 
    - aginst
  validation: 
    openAPIV3Schema: 
      properties: 
        spec:
          properties:
            instanceID:
              description: "Application Gateway Instance unique ID"
              type: string
            desiredBackendPoolResourceVersion:
              description: "Disired Backend Pool Resource Version Applied by Application Gateway Instance"
              type: string
            currentAppliedBackendPoolResourceVersion:
              description: "Current Backend Pool Resource Version Applied by Application Gateway Instance"
              type: string
            lastCheckInTime:
              description: "The Last Timestamp the Application Gateway Instance Checks in the InstanceUpdateStatus CRD Object"
              type: string
            errorMessage:
              description: "(optional) Error Message When Application Gateway Fails to Update the InstanceUpdateStatus CRD Object"
              type: string   